base:
  seed: 12345678
  enable_amp: True
  # data
  dataset_type: kubric
  downsample_factor: 1
  bound: 1
  rescale_scene: False
  enable_scene_contraction: False
  near: 0.1 # useless here
  far: 2 # useless here
  enable_clip_near_far: False
  train_background_color: random
  test_background_color: gray
  # model
  model_type: nerfacto
  render_chunk_size: 16384
  # train.py
  batch_size: 16384
  patch_size: 16
  patch_dilation: 1
  num_img_per_batch: 16
  num_steps: 3000
  warmup_steps: 0
  lr_init: 1.0e-2
  opt_betas: [0.9, 0.999]
  opt_eps: 1.0e-15
  lr_final: 1.0e-3
  lr_decay_mult: 1.0e-8
  eval_render_every: 1000
  eval_images_num: 2
  save_eval_render: True
  use_eval_lpips: False
  save_weight_every: 3000

  finetune_enable: False
  # test.py
  save_test_render: True

model:
  hidden_dim: 256
  geo_feat_dim: 64
  hidden_dim_color: 256
  base_res: 16
  max_res: 8192
  log2_hashmap_size: 21
  features_per_level: 2
  enable_tcnn_mlp: False

  use_appearance_embedding: False
  opaque_background: True

  num_nerf_samples_per_ray: 128
  num_proposal_samples_per_ray: [256]
  num_proposal_iterations: 1
  proposal_net_args_list: [
    {base_res: 16, hidden_dim: 64, log2_hashmap_size: 17, features_per_level: 2, num_levels: 7, max_res: 2048}
  ]
  
  proposal_initial_sampler: uniform
  proposal_histogram_padding: 0.005
  proposal_weights_anneal_max_num_iters: 5000
  
  rgb_loss_type: charb
  distortion_loss_mult: 0.